### ISSUE TITLE
ConceptMap: layout of opening chapter(s)

### ISSUE THREAD

**Issue by seastate** [publicsensors/IntroSensors#6]
This edit seems (to my reading) to be doing a couple different things:

i) It's adding background info on microcontrollers, hardware/software, open source, etc.

ii) It's separating steps of setting up that previously were folded into the Communicating chapter.

iii) It adds installation of drivers and thonny, parallel to but separate from and preceding corresponding sections for mpfshell, beagleterm etc.

Some thoughts:

-- I like the addition of a short Introduction section containing background.  Some of the topics currently in the Setting subsection seem to me to fit better into this Intro -- the titles suggest they are more background than active setting up. So I suggest moving them up before the Setting subsection break.

-- The other parts of the Setting subsection seem to me to break the logical flow in the previous Communicating chapter.

The previous version followed what seemed the most successful sequence in my class: a couple different approaches to USB comms, followed by a couple different approaches to WiFi comms.

In the class and in the book to this point, I've tried to have students use a piece of information immediately after they're given it. That's partly so they remember it, but also because mine was a required class and many of my students felt marginally interested/prepared. Immediate positive feedback seemed important, which is why that section was organized the way it was.

In the current version, the parallel steps of setting up USB drivers and installing thonny in one section and the same steps for other approaches in a separate section seem awkward from a reader's point of view.

I propose retaining the previous order, with the thonny IDE added to the existing sequence in the Communicating (sub-)section.

-- For us, flashing microcontrollers was something we did later in the class, after students had some experience working with microcontrollers. That is, we started with each student having a working microcontroller flashed by the instructors (they flashed another microcontroller later). 

My sense is that flashing instructions are a good candidate for an Appendix. I see two advantages to that placement:

It seems to me most instructors would want to start that way because it removes a big error-prone step from giving students some positive feedback. Students struggling to establish basic comms would have an even harder time if they are trying to set up unflashed boards from the outset.

Flashing is variable and seems to change frequently between microcontrollers, versions and platforms. Discussing it needs to go into some detail, which would not apply or become quickly obsolete in many contexts.

I think it might be off-putting to student to have this content between them and working with their microcontrollers, even if they don't actually have to do the steps -- I think it might be discouraging for some students to be reminded of how much they don't understand before they have some successes. 

Putting these instructions in an Appendix is an attempt to finesse making it available but not conspicuous to readers who don't need it.

But please tell me if you feel differently -- how do you handle flashing in your classes?

**Comment by seastate** [comment]
Yes, I completely agree about different users being better served by different structures. 

We've planned to elaborate the "how to use this book" advice, and maybe having done more of that will make some of these compromises easier.

**Comment by seastate** [comment]
I'm feeling awkward overwriting your edits in main.

Now that my local repo is sync'ed with github, I'm going to start a new branch called newmap2 when I make the next set of ConceptMap edits (leaving off for some other tasks now).

**Comment by jwlauer** [comment]
> Yes, when I do these things on my computer I usually do it with different names like you suggest.
> 
> Let's try doing that, and then we can stay in main. The names can even be informative, indicating author or focal section, where appropriate.
> 
> We'll eventually have to hand edit to merge, but in the meantime it may save a lot of hassles and lost edits.
> 
> It seems to me it is fairly quick and easy to move subsections around, at least compared to writing them in the first place.
> 
> My sense is that a discussion of different microcontrollers might be most useful early, if it is not too technical. Do you want to try out your vision and see how it fits?
> 
> It might then make sense to move the introduction of GPIOs to the Introduction, if that makes explaining what is a microcontroller and what are the relative advantages of different types easier.
> 
> In the big picture, the previous draft of the book was pretty much committed to the ESP8266 Feather. Generalizing to diverse microcontrollers will I think make the first chapters a bit more complicated but the book more broadly useful. I think it's a worthwhile tradeoff, so we can move the content like GPIO intros around to fit the new structure.

Yes, I could make an attempt at a more general overview of microcontrollers.  You are right to point out that it will be challenging to cover relevant details such as GPIO pins, etc., before readers have much understanding of terminology--so perhaps this exercise will push us towards including it mid-way through the book. We'll see.  

If you don't mind, I think I would also like to try to provide a paragraph or two on CircuitPython vs. MicroPython (vs. other language choices).  I say this because I think we are agreed that we should use boards with a Feather form factor for all projects in the textbook--that way, I think all the Fritzing diagrams can be used regardless of actual microcontroller. Readers will wonder why we expect them to get rid of the default CircuitPython that ships on these boards.  

Also, note that long term, being committed to the Feather boards may push us towards using the ESP32-S2 in most textbook projects. I think it's the only of the AdaFruit Feather boards that have been optimized for low current during deep sleep, and it should be much less expensive than the STM feather. My understanding is that there is a rather mature CircuitPython build, but MicroPython is still pretty bleeding edge (e.g., there is no public .bin file). I ordered one yesterday, so it might not be possible to know quite how to frame things until that device arrives.  For now, I think I'll just say that the ESP8266 feather is inexpensive and thus a good choice for learning.

**Comment by seastate** [comment]
I think we have consensus on the main issue here, with additional discussion in future more specifically about distributing content about alternative boards (and possibly on "focal" board choices).

So I'll close this issue; it can be reopened if I'm jumping the gun.
